/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionSuccessRouteImport } from './routes/subscription/success'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReflectRouteImport } from './routes/_app/reflect'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppTodayIndexRouteImport } from './routes/_app/today/index'
import { Route as AppTodayCheckinRouteImport } from './routes/_app/today/checkin'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionSuccessRoute = SubscriptionSuccessRouteImport.update({
  id: '/subscription/success',
  path: '/subscription/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReflectRoute = AppReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayIndexRoute = AppTodayIndexRouteImport.update({
  id: '/today/',
  path: '/today/',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayCheckinRoute = AppTodayCheckinRouteImport.update({
  id: '/today/checkin',
  path: '/today/checkin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/chat': typeof AppChatRoute
  '/plan': typeof AppPlanRoute
  '/reflect': typeof AppReflectRoute
  '/settings': typeof AppSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
  '/today/checkin': typeof AppTodayCheckinRoute
  '/today': typeof AppTodayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/chat': typeof AppChatRoute
  '/plan': typeof AppPlanRoute
  '/reflect': typeof AppReflectRoute
  '/settings': typeof AppSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
  '/today/checkin': typeof AppTodayCheckinRoute
  '/today': typeof AppTodayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/reflect': typeof AppReflectRoute
  '/_app/settings': typeof AppSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
  '/_app/today/checkin': typeof AppTodayCheckinRoute
  '/_app/today/': typeof AppTodayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/chat'
    | '/plan'
    | '/reflect'
    | '/settings'
    | '/oauth/callback'
    | '/subscription/success'
    | '/today/checkin'
    | '/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/chat'
    | '/plan'
    | '/reflect'
    | '/settings'
    | '/oauth/callback'
    | '/subscription/success'
    | '/today/checkin'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pricing'
    | '/_app/chat'
    | '/_app/plan'
    | '/_app/reflect'
    | '/_app/settings'
    | '/oauth/callback'
    | '/subscription/success'
    | '/_app/today/checkin'
    | '/_app/today/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SubscriptionSuccessRoute: typeof SubscriptionSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/success': {
      id: '/subscription/success'
      path: '/subscription/success'
      fullPath: '/subscription/success'
      preLoaderRoute: typeof SubscriptionSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reflect': {
      id: '/_app/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof AppReflectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today/': {
      id: '/_app/today/'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today/checkin': {
      id: '/_app/today/checkin'
      path: '/today/checkin'
      fullPath: '/today/checkin'
      preLoaderRoute: typeof AppTodayCheckinRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppPlanRoute: typeof AppPlanRoute
  AppReflectRoute: typeof AppReflectRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodayCheckinRoute: typeof AppTodayCheckinRoute
  AppTodayIndexRoute: typeof AppTodayIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppPlanRoute: AppPlanRoute,
  AppReflectRoute: AppReflectRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodayCheckinRoute: AppTodayCheckinRoute,
  AppTodayIndexRoute: AppTodayIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SubscriptionSuccessRoute: SubscriptionSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
